### ISSUE TITLE
TypeError: snapshot_download() got an unexpected keyword argument 'allow_regex'

### ISSUE THREAD

**Issue by BohdanVovkotrub** [egorsmkv/wav2vec2-uk-demo#3]
In both "**Demo of Ukrainian wav2vec2 model**" I got an error "`snapshot_download() got an unexpected keyword argument 'allow_regex'` "

Then I tried to run it on my Ubuntu22.04 Virtual Machine.

I did this by next steps:

1) `python3 -m pip install pipenv`
2) `python3 -m pipenv shell`
3) `python -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113`
4) `cd speech_recognition_uk`
5) `pip3 install https://github.com/huggingface/transformers/archive/refs/tags/v4.16.2.zip`
6) `pip3 install https://github.com/kpu/kenlm/archive/master.zip`
7) `sudo apt install git`
8) `git clone https://github.com/egorsmkv/wav2vec2-uk-demo.git`
9) `cd wav2vec2-uk-demo`
10) `python inference.py --model_id Yehor/wav2vec2-xls-r-1b-uk-with-lm --path_files helloworld.wav --chunk_length_s 10 --stride_length_s_l 4 --stride_length_s_r 2`

and then I got the same error as on Website: 

```
-stride_length_s_l 4 --stride_length_s_r 2
Traceback (most recent call last):
  File "/home/bohdan/speech2text/speech_recognition_uk/wav2vec2-uk-demo/inference.py", line 68, in <module>
    main(args)
  File "/home/bohdan/speech2text/speech_recognition_uk/wav2vec2-uk-demo/inference.py", line 9, in main
    processor = Wav2Vec2ProcessorWithLM.from_pretrained(args.model_id)
  File "/home/bohdan/.local/share/virtualenvs/speech_recognition_uk-scP_ij_U/lib/python3.10/site-packages/transformers/models/wav2vec2_with_lm/processing_wav2vec2_with_lm.py", line 174, in from_pretrained
    decoder = BeamSearchDecoderCTC.load_from_hf_hub(
  File "/home/bohdan/.local/share/virtualenvs/speech_recognition_uk-scP_ij_U/lib/python3.10/site-packages/pyctcdecode/decoder.py", line 872, in load_from_hf_hub
    cached_directory = snapshot_download(  # pylint: disable=not-callable
  File "/home/bohdan/.local/share/virtualenvs/speech_recognition_uk-scP_ij_U/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
TypeError: snapshot_download() got an unexpected keyword argument 'allow_regex'
```

**What I doing wrong ?**

**Comment by egorsmkv** [comment]
I think, you need to update transformers and pyctcdecode libraries to the latest versions
